import = ["C:\\Users\\gabif\\AppData\\Roaming\\alacritty\\catppuccin-macchiato.toml"]
shell = "wsl"

[window]
padding = { x = 15 }

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
